// Dummy data for the tables

const crmData = [
  {
    srNo: 1,
    leadID: 1120005000,
    issueDate: 2-4-2025,
    tenderName: "PROCUREMENT, INSTALLATION OF IT EQUIPTS",
    organisation: "SBI",
    bqEoiRfpRfqNitRfi: "RFP",
    stMtNomLt: "MT",
    emd: 20000,
    tenderValue: 0,
    lastDateOfSubmission: 30-4-2025,
    preBidDate: 0 - 0 - 0,
    teamAssigned: "Maketing Team",
    remarks: "",
  },
  {
    srNo: 2,
    leadID: 1120005000,
    issueDate: 2 - 4 - 2025,
    tenderName: "IDENTITY & ACCESS MANAGEMENT SOLUTION",
    organisation: "UCO BANK",
    bqEoiRfpRfqNitRfi: "RFP",
    stMtNomLt: "MT",
    emd: 20000,
    tenderValue: 0,
    lastDateOfSubmission: 30 - 4 - 2025,
    preBidDate: 0 - 0 - 0,
    teamAssigned: "Maketing Team",
    remarks: "",
  },
  {
    srNo: 3,
    leadID: 1120005000,
    issueDate: 2 - 4 - 2025,
    tenderName: "INDIAN GLOBAL MARITIME PLATFORM",
    organisation: "DIRECTORATE GENERAL OF SHIPPING",
    bqEoiRfpRfqNitRfi: "RFP",
    stMtNomLt: "MT",
    emd: 20000,
    tenderValue: 0,
    lastDateOfSubmission: 30 - 4 - 2025,
    preBidDate: 0 - 0 - 0,
    teamAssigned: "Maketing Team",
    remarks: "",
  },
  {
    srNo: 4,
    leadID: 1120005000,
    issueDate: 2 - 4 - 2025,
    tenderName: "INTEGRATED DIGITAL SOLN FOR POCC",
    organisation: "ONGC",
    bqEoiRfpRfqNitRfi: "RFP",
    stMtNomLt: "MT",
    emd: 20000,
    tenderValue: 0,
    lastDateOfSubmission: 30 - 4 - 2025,
    preBidDate: 0 - 0 - 0,
    teamAssigned: "Maketing Team",
    remarks: "",
  },
  {
    srNo: 5,
    leadID: 1120005000,
    issueDate: 2 - 4 - 2025,
    tenderName: "SI FOR ERP SOLUTION",
    organisation: "BIHAR STATE ELECTRONICS DEVELOPMENT CORP",
    bqEoiRfpRfqNitRfi: "RFP",
    stMtNomLt: "MT",
    emd: 20000,
    tenderValue: 0,
    lastDateOfSubmission: 30 - 4 - 2025,
    preBidDate: 0 - 0 - 0,
    teamAssigned: "Maketing Team",
    remarks: "",
  },
];

export default crmData;
