export const mockLostDomesticLeads = [
  {
    id: 1,
    serialNumber: "DL-001",
    tenderName: "Railway Infrastructure Development",
    customer: "Ministry of Railways",
    tenderType: "RFP",
    typeBid: "Technical",
    valueWithoutGST: 50000000,
    valueWithGST: 59000000,
    reasonLosing: "Price not competitive",
    year: 2025,
    partner: "ABC Corp",
    status: "Lost",
    createdAt: "2025-11-15"
  },
  {
    id: 2,
    serialNumber: "DL-002",
    tenderName: "Highway Maintenance Project",
    customer: "National Highways Authority",
    tenderType: "Single Tender",
    typeBid: "Financial",
    valueWithoutGST: 75000000,
    valueWithGST: 88500000,
    reasonLosing: "N/A",
    year: 2025,
    partner: "XYZ Ltd",
    status: "Won",
    createdAt: "2025-11-20"
  },
  {
    id: 3,
    serialNumber: "DL-003",
    tenderName: "Water Supply System",
    customer: "Municipal Corporation",
    tenderType: "EOI",
    typeBid: "Combined",
    valueWithoutGST: 30000000,
    valueWithGST: 35400000,
    reasonLosing: "Technical requirements not met",
    year: 2025,
    partner: "",
    status: "Lost",
    createdAt: "2025-11-18"
  },
  {
    id: 4,
    serialNumber: "DL-004",
    tenderName: "Building Construction",
    customer: "State Government",
    tenderType: "RFP",
    typeBid: "Technical",
    valueWithoutGST: 100000000,
    valueWithGST: 118000000,
    reasonLosing: "",
    year: 2025,
    partner: "DEF Partners",
    status: "Pending",
    createdAt: "2025-11-22"
  },
  {
    id: 5,
    serialNumber: "DL-005",
    tenderName: "IT Infrastructure Setup",
    customer: "Private Bank",
    tenderType: "BQ",
    typeBid: "Financial",
    valueWithoutGST: 20000000,
    valueWithGST: 23600000,
    reasonLosing: "",
    year: 2025,
    partner: "",
    status: "Won",
    createdAt: "2025-11-10"
  }
];